// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

package trace

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Trace struct {
	Start            *int64   `protobuf:"varint,2,req,name=start" json:"start,omitempty"`
	End              *int64   `protobuf:"varint,3,req,name=end" json:"end,omitempty"`
	Message          []string `protobuf:"bytes,4,rep,name=message" json:"message,omitempty"`
	Child            []*Trace `protobuf:"bytes,5,rep,name=child" json:"child,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Trace) Reset()         { *m = Trace{} }
func (m *Trace) String() string { return proto.CompactTextString(m) }
func (*Trace) ProtoMessage()    {}

func (m *Trace) GetStart() int64 {
	if m != nil && m.Start != nil {
		return *m.Start
	}
	return 0
}

func (m *Trace) GetEnd() int64 {
	if m != nil && m.End != nil {
		return *m.End
	}
	return 0
}

func (m *Trace) GetMessage() []string {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Trace) GetChild() []*Trace {
	if m != nil {
		return m.Child
	}
	return nil
}

func init() {
}
